# Generated by Django 5.0.4 on 2024-06-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="userregister",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=200)),
                ("last_name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=200)),
                ("birthday", models.CharField(blank=True, max_length=20, null=True)),
                ("state", models.CharField(blank=True, max_length=30, null=True)),
                ("country", models.CharField(blank=True, max_length=30, null=True)),
                ("gender", models.CharField(blank=True, max_length=30, null=True)),
                ("pincode", models.CharField(blank=True, max_length=30, null=True)),
                ("address", models.CharField(blank=True, max_length=1000, null=True)),
                ("age", models.CharField(blank=True, max_length=30, null=True)),
                ("contact", models.CharField(blank=True, max_length=20, null=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="media")),
            ],
        ),
    ]
