# Generated by Django 5.0.4 on 2024-06-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("generator", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("author", models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name="userregister",
            name="address",
        ),
        migrations.RemoveField(
            model_name="userregister",
            name="age",
        ),
        migrations.RemoveField(
            model_name="userregister",
            name="birthday",
        ),
        migrations.RemoveField(
            model_name="userregister",
            name="contact",
        ),
        migrations.RemoveField(
            model_name="userregister",
            name="country",
        ),
        migrations.RemoveField(
            model_name="userregister",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="userregister",
            name="image",
        ),
        migrations.RemoveField(
            model_name="userregister",
            name="pincode",
        ),
        migrations.RemoveField(
            model_name="userregister",
            name="state",
        ),
    ]
