# Generated by Django 5.0.1 on 2024-07-01 16:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("generator", "0002_quote_remove_userregister_address_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="userregister",
        ),
    ]
